version: '3.1'

services: 
  db: 
    image: mysql
    restart: always
    environment: 
      MYSQL_DATABASE: transaction_centralization
      MYSQL_ROOT_PASSWORD: root123
    ports: 
      - "3306:3306"


